<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>036c594c-0837-4849-a9ec-202ecf2efa63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>208c75c0-1b9e-4f6a-80d5-0d1496563105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>328b8e8c-fe53-4dd4-8bb9-cc830ec226d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>8087995a-e02a-4b3d-8f1d-5fb9c6e1e70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://github.com//sakinala/AutomationTesting/raw/master/samplefile.pdf</value>
      <webElementGuid>f4de614e-b319-4faf-a1b4-a5f321c810ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>fcd16169-56d1-4e00-ae97-8cde58d977bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;cont_box&quot;]/div[1]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>c874c766-effd-4d80-a6c4-2b837652121f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='button']</value>
      <webElementGuid>6daf6ccf-afa2-4847-80c9-670d6e239932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[2]</value>
      <webElementGuid>c7d5ddb2-cd24-42c5-b9a1-86d20f251cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Download Demo for Automation'])[1]/following::a[1]</value>
      <webElementGuid>7ab6b1fc-686c-4071-bb37-638184638c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Site'])[1]/following::a[1]</value>
      <webElementGuid>2848ea5a-8492-449d-a5e4-afc3fa4602bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generated Text File to Download'])[1]/preceding::a[1]</value>
      <webElementGuid>99f82dd4-9605-4702-860c-3a480d2508ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Data:'])[1]/preceding::a[1]</value>
      <webElementGuid>f50e2a24-a5be-4930-8e3b-93403a617d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>79e91980-2bb3-410e-b465-749422958137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://github.com//sakinala/AutomationTesting/raw/master/samplefile.pdf')]</value>
      <webElementGuid>dfdbeb5a-91b1-404c-9223-50e1e80516d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/a</value>
      <webElementGuid>8fd91cec-5caf-41ca-acde-545bf3d63e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @href = 'https://github.com//sakinala/AutomationTesting/raw/master/samplefile.pdf' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>2bc60b31-a361-4fe5-b652-783cbd135298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
